Adicionado heranca
DantasB/CSharp4Noobs pull request #11
Opened 2021-04-16 13:21 UTC by igortauh

2021-04-16 13:41 UTC, DantasB commented
@igortauh ficou muito bom, mas acho que seria interessante adicionar um exemplo genérico com as duas classes. Motivo: A pessoa que estiver lendo poderia testar o código no seu próprio compilador para verificar como funciona a herança. (2 classes em um mesmo namespace para evitar erros de compilação). 
Vou dar um review approved mas fica essa sugestão :D.

2021-04-16 13:42 UTC, DantasB reviewed
@igortauh ficou muito bom, mas acho que seria interessante adicionar um exemplo genérico com as duas classes. Motivo: A pessoa que estiver lendo poderia testar o código no seu próprio compilador para verificar como funciona a herança. (2 classes em um mesmo namespace para evitar erros de compilação).
Vou dar um review approved mas fica essa sugestão :D.

2021-04-16 13:44 UTC, igortauh commented
> @igortauh ficou muito bom, mas acho que seria interessante adicionar um exemplo genérico com as duas classes. Motivo: A pessoa que estiver lendo poderia testar o código no seu próprio compilador para verificar como funciona a herança. (2 classes em um mesmo namespace para evitar erros de compilação).
> Vou dar um review approved mas fica essa sugestão :D.

Pode deixar, hj de tarde eu adiciono :)

2021-04-16 17:00 UTC, igortauh commented
> @igortauh ficou muito bom, mas acho que seria interessante adicionar um exemplo genérico com as duas classes. Motivo: A pessoa que estiver lendo poderia testar o código no seu próprio compilador para verificar como funciona a herança. (2 classes em um mesmo namespace para evitar erros de compilação).
> Vou dar um review approved mas fica essa sugestão :D.

Olá, Daniel. Irei fazer o exemplo agora, você acha que seria melhor deixar as duas classes no mesmo arquivo?

2021-04-16 20:40 UTC, Logikoz requested changes

2021-04-16 21:09 UTC, DantasB commented on docs/4-Intermediario/03-Heranca.md
> +Podemos pensar em uma relação de "Pai" e "Filho", onde o filho HERDA todas as características do pai (atributos e métodos). Vejamos um exemplo:
@Logikoz tá sim, atributo é sinônimo de propriedade em alguma bibliografias. Porém, para evitar essa ambiguidade acho válido botar um atributos (ou propriedades).

2021-04-16 21:16 UTC, DantasB reviewed
Agora sim, o exemplo ficou muito bom!!!
OBS: Meu nome é Bruno hahaha. (DantasB = Bruno Dantas)

2021-04-16 21:31 UTC, igortauh commented
> Agora sim, o exemplo ficou muito bom!!!
> OBS: Meu nome é Bruno hahaha. (DantasB = Bruno Dantas)

Eita, desculpa kkkkk. Eu li rápido no começo.

2021-04-16 21:32 UTC, Logikoz commented on docs/4-Intermediario/03-Heranca.md
> +Podemos pensar em uma relação de "Pai" e "Filho", onde o filho HERDA todas as características do pai (atributos e métodos). Vejamos um exemplo:
[Teste] //[atributo](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/concepts/attributes/)
public string Teste {get;set;} //[propriedade](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/classes-and-structs/properties)
private string teste; //[campo](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/classes-and-structs/fields)

em c# usar o termo atributo para se referir a uma propriedade não gera uma ambiguidade, pois sao coisas totalmente distintas.

existe a semelhança de outras linguagens (php e java, por exemplo) que usam o termo atributo para o equivalente a campos no c#.

2021-04-16 21:34 UTC, igortauh commented on docs/4-Intermediario/03-Heranca.md
> +Podemos pensar em uma relação de "Pai" e "Filho", onde o filho HERDA todas as características do pai (atributos e métodos). Vejamos um exemplo:
Realmente me equivoquei aqui, seria propriedades mesmo. Sou meio iniciante no git, eu posso alterar o arquivo e comitar novamente?

2021-04-16 21:37 UTC, Logikoz commented on docs/4-Intermediario/03-Heranca.md
> +Podemos pensar em uma relação de "Pai" e "Filho", onde o filho HERDA todas as características do pai (atributos e métodos). Vejamos um exemplo:
@igortauh primo, pode sim.

assim que vc commitar e dar push ja cai reflete aqui automatico!

2021-04-16 21:46 UTC, igortauh commented on docs/4-Intermediario/03-Heranca.md
> +Podemos pensar em uma relação de "Pai" e "Filho", onde o filho HERDA todas as características do pai (atributos e métodos). Vejamos um exemplo:
Prontinho, ajeitei todas as ocorrências

2021-04-17 04:45 UTC, Logikoz approved these changes
Top!

2021-04-17 04:45 UTC, merged